# Generated by Django 5.1.3 on 2024-11-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_spare_alter_bb_options_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to='rubric',
        ),
    ]
